name: camera_app
description: "A security camera application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Network and API
  dio: ^5.4.0
  json_annotation: ^4.8.1
  
  # Camera and Media
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # WebRTC for streaming
  flutter_webrtc: ^0.9.47
  
  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
