name: security_camera_app
description: Security camera application that turns your phone into a surveillance camera

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_webrtc: ^0.9.47
  provider: ^6.1.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  wakelock: ^0.6.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
